spring:
  application:
    name: libraff-store
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/libraff-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080